export enum AnimationName {
    PlayerDeath,
    Immortality,
    CoinIddle,
    EnemyDeath,
    BirdIddle,
    DragonflyIddle,
    ButterflyIddle,
    FiverIddle,
    PhantomIddle,
    PlayerIddle,
    PlayerMoveUp,
    PlayerMoveDown,
    PlayerMoveForward,
}
